### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by chrisghardwick** [Wildhoney/ngVideo#25]
Is this project still alive? 

The example has some problems:
The vendor files for bootstrap, angularjs and common.js are missing.

I don't want to utilize a dead project.

Thanks!

**Comment by Wildhoney** [comment]
Yep, it's still alive :+1: if you want to submit a PR for those, then please by all means.

**Comment by chrisghardwick** [comment]
Thanks. Let me get up and running on the project.

**Comment by Wildhoney** [comment]
It also has an issue that it communicates to the directive through a service, which is a singleton, rather than the directive's interface. I'm currently in the progress of refactoring this. Although it won't cause any issues unless you have more than one video element on the page.

**Comment by chrisghardwick** [comment]
I might be missing something, but I downloaded the source and the components are missing. I was expecting to see the directives mentioned in the documentation in the Components folder (https://github.com/Wildhoney/ngVideo/tree/master/components) or in the distributable: https://github.com/Wildhoney/ngVideo/blob/master/dist/ng-video.js custom folder: https://github.com/Wildhoney/ngVideo/tree/master/dist/custom

Specifically I was looking for buffer, controls, etc. directives.

Is there something I missing here?

**Comment by Wildhoney** [comment]
Sorry &mdash; they [should be there now](https://github.com/Wildhoney/ngVideo/tree/master/components).
