### ISSUE TITLE
vi-timeline is not moving while the video is playing

### ISSUE THREAD

**Issue by Sobiru** [Wildhoney/ngVideo#35]
So i have this problem, I'm using vi-timeline directive to see where I'm currently at in the video, but as the video is playing, the slider doesn't move an inch.

If i click on it and slide it right and left, the video does go back and forth but again while the video is playing, the slider doesn't move.

Is there something I'm missing? 

Thank you.

**Comment by Wildhoney** [comment]
Is your `vi-timeline` directive a child of the `vi-feedback` directive? As it needs to be :+1: The current version relies heavily on the structure of your document.

**Comment by Sobiru** [comment]
Thank you @Wildhoney, that was it.
I'll close down the issue.
