### ISSUE TITLE
setVolume on initialization

### ISSUE THREAD

**Issue by nmpribeiro** [Wildhoney/ngVideo#42]
Hi there!

In my particular case I need to start the video muted. Haven't found anything on docs about it.

How can I setVolume(x) on initialization? I mean, I can use the controller to grab the apropriate scope where the interface is, but... shouldn't we be able to access directly the controls from the controller? 

Thanks in advance

**Comment by Wildhoney** [comment]
> shouldn't we be able to access directly the controls from the controller?

Agreed! This will definitely be in the next version &mdash; which will be written with Angular2.

For the moment you can add the `muted` attribute to the `video` element:

```html
<video muted vi-screen></video>
```

Please let me know how you get on with that.

**Comment by nmpribeiro** [comment]
Great! Thanks @Wildhoney :+1: 
Tried 'mute' already, forgot about the past tense heh
Then guess we could start muted untill Angular2 ngVideo :)
