### ISSUE TITLE
poster image or check if video valid?

### ISSUE THREAD

**Issue by nmpribeiro** [Wildhoney/ngVideo#43]
Hi there!

I'm getting a little dificulty understanding how to check if the video feed is valid.... should I do it before giving a src to ngVideo or is there some feature already in place?

ngVideo is based on http://www.html5rocks.com/en/tutorials/video/basics/ right? How can I assign a poster image? docs say nothing about it...

Should we do it on the screen directive?

`
<video vi-screen loop muted autoplay preload="auto" poster="{{item.bgImg}}"></video>
`

Thanks

**Comment by Wildhoney** [comment]
You should be able to add the `poster` property to `<video />` without any problems.

For the fallback you can use the [multi-source approach](https://github.com/Wildhoney/ngVideo/blob/master/components/Service.js#L86]. Unfortunately there's no way to check which videos are valid &mdash; you can only supply a list of various formats and hope one is supported by the browser. You could fallback to [`poster` attribute](http://www.w3schools.com/tags/att_video_poster.asp) which should display if none of the videos play.

**Comment by nmpribeiro** [comment]
thanks @Wildhoney  :+1:
