### ISSUE TITLE
Endless video playlist.

### ISSUE THREAD

**Issue by SergeyBondarenko** [Wildhoney/ngVideo#45]
Hello.
I have 5 videos. And I want to play this playlist forever. The 1st video will start automatically after the 5th video. How can it be implemented? Thank you.

**Comment by Wildhoney** [comment]
Please try attaching the [`loop`](http://www.w3schools.com/tags/att_video_loop.asp) attribute to the `video` element &mdash; as far as I remember I implemented this.

**Comment by SergeyBondarenko** [comment]
Thank you.
